### ISSUE TITLE
Incomplete sentence in the wiki

### ISSUE THREAD

**Issue by jcranky** [esa-prl/ExoMy#10]
Hi :)

I just started reading the wiki, to learn a bit more about how to put this together. There is a sentence that seems to be cut, here:

![Selection_143](https://user-images.githubusercontent.com/772886/104110201-a08c6800-52d5-11eb-8357-0e62be5d95ea.png)

Allows what?
Not a big deal, of course.

**Comment by maxehrhardt** [comment]
Thanks for pointing this out. Looks not so good, especially on the first page.
I fixed it!
