### ISSUE TITLE
Control web page not working without Internet connection

### ISSUE THREAD

**Issue by berendj** [esa-prl/ExoMy#11]
In the website to control the ExoMy the javascript is loaded from Internet. This means that in the open field, wanting to run the ExoMy via it's  own WiFi will not be successful.

**Comment by maxehrhardt** [comment]
Was solved by https://github.com/esa-prl/ExoMy_Software/pull/21#issue-583141024 for ROS1 and https://github.com/esa-prl/ExoMy_Software/pull/19#issue-580808201  for ROS2.
