### ISSUE TITLE
Error during installation of Docker

### ISSUE THREAD

**Issue by berendj** [esa-prl/ExoMy#12]
During installation of Docker I got this error:
E: Sub-process /usr/bin/dpkg returned an error code (1)

According [raspberrypi.stackexchange.com](https://raspberrypi.stackexchange.com/questions/103709/installing-docker-on-raspberry-pi) this can happen after upgrading the Raspberry Pi. Some of the upgraded parts are not loaded until the next reboot, causing the Docker install to fail.

Please add in the Wiki a sudo reboot now after sudo apt-get update and sudo apt-get full-upgrade before installingen Docker.

**Comment by maxehrhardt** [comment]
Good point. I added an information in the wiki:
https://github.com/esa-prl/ExoMy/wiki/Software-Instructions#install-software
