### ISSUE TITLE
Cable protection required

### ISSUE THREAD

**Issue by 0xD0M1M0** [esa-prl/ExoMy#14]
During driving the rover the cable tend to get caught in the wheels or rub against the "P03_Bogie_Bearing_Default". In my case I saw after a few hours of test driving serious cable wear.

I used following solutions combinations to protect or mitigate the risk of cable wear:
- all cables are wrapped longitunal carefully in electrical tape on exposed areas until they are inside the housing. Exposed areas are: inside the "P28_Wheel_Bracket" (specifically on the top turn), after leaving the "P28_Wheel_Bracket" until passing the first zip tie inside the "P19_Bogie" and passing through the "P03_Bogie_Bearing"
- used the unconventional rubber band solution to tie the cables into an upward direction between "P28_Wheel_Bracket" and "P19_Bogie". In the rear the rubber band goes to the outer zip tie position around the bogie, in the front upwards around the motor and in the center also around the motor
- in the center, I exited the cable on the top of the "P28_Wheel_Bracket" by removing on each side of "P29_Wheel_Bracket_Fixing_Plate_Default" one end that slides under the "P28_Wheel_Bracket" allowing for enough space to exit the cables. Afterwards I was able to pull up the cable with the rubber band.

One open spot for the cables are the "exits" outside the "P28_Wheel_Bracket". Currently I use shrink tubes that are cut open and then clamped into the whole setup. But they tend to fall out.

Maybe these topics can be addressed in the wiki in the appropriate chapters. This would allow a longer lasting experience while driving the rover.

**Comment by maxehrhardt** [comment]
Great work! I will have a look on how to add those information to the wiki.
Can you provide some explaining pictures for the parts that needed to be fixed?
It is mostly easier to show stuff, then to explain.

**Comment by 0xD0M1M0** [comment]
Here are some pictures. You will notice, that instead of opening the motors for cable routing, I added golden motor covers. This saved me some trouble. Currently, the rear bogie has no electrical tape as it the cables never went close to the wheel due to the rubber bands. The electrical tape makes the cables quite stiff. Therefore I tried once to also tape the "exits" from "P28_Wheel_Bracket", but that didn't go to well as the cable was bend not nicely, risking a cable break from the inside.

I currently have the bogie covers on so, sadly no quick pictures of the protected cables through the "P03_Bogie_Bearing".

![P29_Wheel_Bracket_Fixing_Plate_Default](https://user-images.githubusercontent.com/76812428/109838781-c2a3c600-7c46-11eb-8e6f-7c6b49b19961.png)
-> Shows the two different modes for "P29_Wheel_Bracket_Fixing_Plate_Default" for the center wheels.
![P3030225](https://user-images.githubusercontent.com/76812428/109838802-c8011080-7c46-11eb-8591-a5191119712e.JPG)
-> Here you see the cable routing for the center wheels
![P3030223](https://user-images.githubusercontent.com/76812428/109838789-c59eb680-7c46-11eb-9fe9-9a7eff128ded.JPG)
-> Rear wheel assembly with rubber band alignment. Here two small dropshaped cuts in the "P19_Bogie_Rear Bogie" on both sides to fix the rubber band without my need of a zip tie would make it look even better. 
![P3030224](https://user-images.githubusercontent.com/76812428/109838797-c6cfe380-7c46-11eb-99df-8d45db577ad4.JPG)
-> Rear wheel assembly with rubber band alignment. You can see here the shrink tube coming out of the wheel assembly. But this is not perfect. I tried stretching the shrink tube to fit it over the connector, so I don't have to cut it open, but with a 2 cm long piece, it was not easy. Maybe a bigger shrink tube could help, but they are currently not part of the BoM, so I didn't have them.
![P3030226](https://user-images.githubusercontent.com/76812428/109838805-c9323d80-7c46-11eb-96c7-d52eeceb7c26.JPG)
-> Front wheel assembly with rubber band alignment.
![P3030227](https://user-images.githubusercontent.com/76812428/109838809-c9cad400-7c46-11eb-995c-e1fd406c11fe.JPG)
-> Front wheel assembly with rubber band alignment and motor cover.

**Comment by 0xD0M1M0** [comment]
The wiki was updated on the following pages to address this issue:

[Purchasing Instructions](https://github.com/esa-prl/ExoMy/wiki/Purchasing-Instructions)
[Bogie Assembly](https://github.com/esa-prl/ExoMy/wiki/Bogie-Assembly)
