### ISSUE TITLE
CAD drawings

### ISSUE THREAD

**Issue by edhage** [esa-prl/ExoMy#15]
Hello, could you please save the CAD drawings in Step-format so I (and probably many others) can read it in any CAD-program? (Tried to read it in Inventor 2018 that recognises sldprt and sldasm, but the 2018 was too old).

**Comment by edhage** [comment]
I see step is added in the release-file. So very good. However, an assembly would be appreciated.

**Comment by mvoellmy** [comment]
Hey!
The file ```A01_ExoMy_Default.step``` is an assembly of the whole rover. It's in the same folder ```ExoMy Release/Parts/STEP```as the other step files.
Cheers
Miro

**Comment by edhage** [comment]
thanks for the info
