### ISSUE TITLE
Funktion

### ISSUE THREAD

**Issue by GGoergen** [esa-prl/ExoMy#21]
My ExoMy is ready, everything calibrated. Now when I turn it on I can't access the WebGui, neither does the remote control via gamepad work. Nothing moves. The Raspi can be operated via HDMI, keyboard and mouse, the ServoHat also works???

**Comment by 0xD0M1M0** [comment]
Hello @GGoergen,
I am happy to help. The easiest and best way is to join the Discord community (https://discord.gg/gZk62gg) for Exomy and ask the question there. There are many people happy to help and maybe makes the communication easier.

If you like to stay here, please provide the setup and how far you progressed in the assembly and startup wiki entry.

**Comment by 0xD0M1M0** [comment]
Solved by GGoergen:

> Tip from the ExoMy WIKI: ROS cant find files
> Try sourcing the ROS development environment again with source devel/setup.bash. This command should be executed in the exomy_ws. That's needed when a new terminal is started.
