### ISSUE TITLE
Number of required servos is unclear (16 or 12?)

### ISSUE THREAD

**Issue by MartinSpiessl** [esa-prl/ExoMy#3]
Thanks for making this project open source/open hardware!

I have a small question regarding the required components.
The BOM states that we need the following:

```
6 | Parallax-Servo | Steering Modded
10 | Parallax-Servo | Continuous
```

But from the building instructions I could only find that 6 of each (= 12 servos total) are used in the bogie.  
What is the intended use for the other servos?  
Where these simply left on the BOM, e.g. because you originally planned to make the head orientable?

**Comment by mvoellmy** [comment]
You're welcome :) You are right, ExoMy only needs 12 motors (6 for steering and 6 for driving).
In which BoM did you find that 10 coninuous servos are needed? In the .xlsx and the .pdf it mentions correctly 6 each:
![image](https://user-images.githubusercontent.com/10925797/96336838-8a7a5d00-1082-11eb-9729-7908ac0ba125.png)

![image](https://user-images.githubusercontent.com/10925797/96336846-a0881d80-1082-11eb-847b-1b0c4955950a.png)

**Comment by mvoellmy** [comment]
Also we would be happy if you join our discord server and to share your progress :)

https://discord.gg/gZk62gg

**Comment by MartinSpiessl** [comment]
I know see what happened. I had the collapsed version of BOM so I didn't realize the first column are actually increasing IDs but misinterpreted them as part counts.

Thanks for the clarification!

> Also we would be happy if you join our discord server and to share your progress :)

Thank you, maybe in time I will. I have not yet started, I was just trying to get an overview of the involved components.
