### ISSUE TITLE
BOM xlsx file contains hidden rows which might be overlooked by people

### ISSUE THREAD

**Issue by MartinSpiessl** [esa-prl/ExoMy#4]
When I open https://github.com/esa-prl/ExoMy/wiki/v1.0.2/BoM/PI_ExoMy_Purchasing_BoM.xlsx in libreoffice, some of the rows are not displayed by default.  

This can be confusing to people, as they might not be aware that the file also contains detailed information about the other parts as well.

They might then try to figure out the details from https://github.com/esa-prl/ExoMy/wiki/v1.0.2/Technical_Drawings/PDF/PI_ExoMy_All_Parts_BoM.pdf which will lead to frustration, since the information there is not detailed enough for actually purchasing the parts.

**Comment by mvoellmy** [comment]
Good find! The rows are hidden due to a filter that was commited and pushed accidentally. I updated the file and it should now show all parts again by default.
