### ISSUE TITLE
some website wiki improvement suggestions

### ISSUE THREAD

**Issue by pebe-espana** [esa-prl/ExoMy#5]
links to "wiki" do not lead to explanation wiki - see annotated screenshot
<img width="1112" alt="Screenshot 2020-10-31 at 10 25 45" src="https://user-images.githubusercontent.com/70989216/97775865-57e16180-1b64-11eb-8b96-ac335cedf489.png">

**Comment by pebe-espana** [comment]
Now same "problem" permeates the site - what is needed is that references to wiki should point to a page (like content page) of the links on the right hand side bulleted list. Repeatedly ran into just wanting to look up some point and clicking on wiki or title of a para that lead to the same page. so extra content table page could help?

**Comment by pebe-espana** [comment]
In the instructions for Bogie assembly, maybe a diagram as attached could be helpful to indicate the 180 degree swing range wanted? Although photos are helpful, it is easy to get all confused what the end result should be. (In fact, I hope I got it right ;-) )
![bogies](https://user-images.githubusercontent.com/70989216/97776495-db9d4d00-1b68-11eb-8e7f-b0c5e1c2dacd.png)

**Comment by maxehrhardt** [comment]
The wiki README has been updated with more useful links and text. The instruction schematic for the bogies is in the making.

**Comment by mvoellmy** [comment]
Added a schematic indicating the desired range of motion. Thanks for the inputs @pebe-espana!
