### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by j-dohnalek** [esa-prl/ExoMy#7]
**Problem:**

https://github.com/esa-prl/ExoMy/wiki/Bogie-Assembly#install-steering-motors

the  bill of materials does not say M4x12 it only says M4x10

![image](https://user-images.githubusercontent.com/6439903/103095658-4d3dc880-45f9-11eb-9704-9e63e9e57870.png)

**Solution:**

Change the instructions to M4x10

**Comment by mvoellmy** [comment]
Thanks! Fixed it.
